obstacle_range: 2.5
raytrace_range: 3.0
footprint: [[-0.5, -0.33], [-0.5, 0.33], [0.5, 0.33], [0.5, -0.33]]
footprint_padding: 0.01
# robot_radius: 0.5
inflation_radius: 0.55
observation_sources: scan
scan: {data_type: LaserScan, topic: /scan, marking: true, clearing: true}
# laser_scan_sensor: {sensor_frame: X1/base_link, data_type: LaserScan, topic: /scan, marking: true, clearing: true}
#
# point_cloud_sensor: {sensor_frame: frame_name, data_type: PointCloud, topic: topic_name, marking: true, clearing: true}
